In [1]:
import numpy as np

### Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [48]:
arr = np.arange(2,14).reshape(4,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

### Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20) 


In [50]:
arr1 = np.random.randint(1,50,20)
print(arr1)
arr1[arr1%2 != 0] = -1
arr1

[35  3 19 45 20 22  2 28 32  4 29  6 28  5 28 12 46 32 46 30]


array([-1, -1, -1, -1, 20, 22,  2, 28, 32,  4, -1,  6, 28, -1, 28, 12, 46,
       32, 46, 30], dtype=int32)

### Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999. 
#### a. Create a 1d-array of mobile phones prices 

In [55]:
arr2 = np.array([6999,7500,11999,27899,14999,9999])
arr2
arr2.ndim

1

#### b. Convert this array to float type 

In [72]:
arr4 = arr2.astype('float64')
arr4.dtype

dtype('float64')

#### c. Append a new mobile having price of 13999 Rs. to this array 

In [57]:
arr2 = np.append(arr2, 13999)
arr2

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

#### d. Reverse this array of mobile phones prices 

In [58]:
arr2[::-1]

array([13999,  9999, 14999, 27899, 11999,  7500,  6999])

#### e. Apply GST of 18% on mobile phones prices and update this array.

In [59]:
arr3=arr2*1.18
arr3

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

#### f. Sort the array in descending order of price 

In [79]:
np.sort(arr2)[::-1]

array([27899, 14999, 13999, 11999,  9999,  7500,  6999])

In [80]:
arr2

array([ 6999,  7500,  9999, 11999, 13999, 14999, 27899])

#### g. What is the average mobile phone price 

In [62]:
arr2.mean()

np.float64(13342.0)

#### h. What is the difference b/w maximum and minimum price 

In [63]:
arr2.max() - arr2.min()

np.int64(20900)

###  Find out the indices of non zero element in given array  [1,2,0,0,4,0]

In [64]:
arr3 = np.array([1,2,0,0,4,0])
arr3

array([1, 2, 0, 0, 4, 0])

In [65]:
arr3.nonzero()

(array([0, 1, 4]),)