In [2]:
import numpy as np

### 1. Create a NumPy array containing integers from 0 to 9.

In [3]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [5]:
arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [9]:
arr3 = np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between

In [13]:
arr4 = np.random.randint(1,50,(5,4))
arr4


array([[ 2,  1, 37, 32],
       [ 8, 19, 39, 38],
       [33,  7,  8, 43],
       [ 6, 24,  8,  1],
       [14, 45, 37,  5]], dtype=int32)

In [14]:
arr4.shape

(5, 4)

In [15]:
arr4.size

20

### 5. Create a 3x3 array of integers and access:
#### a. The second element of the first row.

In [16]:
arr5 = np.random.randint(1,50,(3,3))
arr5

array([[14, 36,  2],
       [44, 26, 35],
       [34, 13, 14]], dtype=int32)

In [18]:
arr5[:1,1]

array([36], dtype=int32)

#### b. The third column of the 2nd row.

In [20]:
arr5[1,2]

np.int32(35)

#### c. A subarray with the first two rows and last two columns.

In [21]:
arr5[:2,1:]

array([[36,  2],
       [26, 35]], dtype=int32)

### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [23]:
arr6 = np.arange(1,13)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
a=arr6.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 7. Reshape a 3x3 matrix into a 1D array.

In [36]:
arr7 = np.random.randint(1,50,(3,3))
arr7

array([[16, 31, 18],
       [18, 39, 43],
       [28, 16, 30]], dtype=int32)

In [37]:
b = arr7.reshape(-1)
b

array([16, 31, 18, 18, 39, 43, 28, 16, 30], dtype=int32)

### 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
### subtraction, multiplication, and division on them.

In [39]:
a = np.random.randint(1,12,(2,3))
b = np.random.randint(20,40,(2,3))
a

array([[ 8,  8,  9],
       [11,  2,  3]], dtype=int32)

In [40]:
b

array([[37, 24, 38],
       [20, 25, 36]], dtype=int32)

In [41]:
a+b

array([[45, 32, 47],
       [31, 27, 39]], dtype=int32)

In [42]:
b-a

array([[29, 16, 29],
       [ 9, 23, 33]], dtype=int32)

In [43]:
a*b

array([[296, 192, 342],
       [220,  50, 108]], dtype=int32)

In [44]:
b/a

array([[ 4.625     ,  3.        ,  4.22222222],
       [ 1.81818182, 12.5       , 12.        ]])

### 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a
### given array.

In [45]:
arr9 = np.random.randint(1,12,(2,3))
arr9

array([[ 4,  8,  3],
       [ 3,  6, 10]], dtype=int32)

In [46]:
arr9.sum()

np.int64(34)

In [47]:
arr9.mean()

np.float64(5.666666666666667)

In [49]:
a = np.std(arr9)
a

np.float64(2.6246692913372702)

### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
### the @ operator.

In [50]:
a = np.random.randint(1,12,(2,2))
b = np.random.randint(20,40,(2,2))

In [51]:
a

array([[ 5, 11],
       [ 7,  6]], dtype=int32)

In [52]:
b

array([[37, 35],
       [25, 27]], dtype=int32)

In [53]:
np.dot(a,b)

array([[460, 472],
       [409, 407]], dtype=int32)

In [54]:
a @ b

array([[460, 472],
       [409, 407]], dtype=int32)

### 11. Find the transpose of matrix A and matrix B.

In [56]:
np.transpose(a)

array([[ 5,  7],
       [11,  6]], dtype=int32)

In [57]:
np.transpose(b)

array([[37, 25],
       [35, 27]], dtype=int32)

### 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
### Explain how broadcasting works in this operation.

### 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the
### entire array.

In [58]:
a13 = np.random.randint(1,50,(4,4))
a13

array([[47,  2,  3, 14],
       [43, 30, 36, 34],
       [42, 48, 39, 31],
       [29, 45, 16, 41]], dtype=int32)

In [60]:
a13.max()

np.int32(48)

In [61]:
a13.min()

np.int32(2)

In [62]:
a13.mean()

np.float64(31.25)

### 14. Find the row-wise and column-wise sums.

In [64]:
a14 = np.random.randint(1,20,(3,3))
a14

array([[12, 13,  5],
       [18, 11,  1],
       [ 3,  7, 17]], dtype=int32)

In [67]:
np.sum(a14,axis=0)  # column wise sum

array([33, 31, 23])

In [69]:
np.sum(a14,axis=1)   #row wise sum

array([30, 30, 27])

### 15. Generate an array of 10 random integers between 1 and 50.

In [70]:
a15 = np.random.randint(1,50,(10,))
a15

array([18,  7, 21, 21, 39, 24, 28, 19, 32, 40], dtype=int32)

In [71]:
a15.size

10

### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [74]:
a16 = np.random.rand(25).reshape(5,5)
a16

array([[0.98878997, 0.55457966, 0.5868858 , 0.80540741, 0.88464321],
       [0.93728088, 0.24568249, 0.14842218, 0.11437037, 0.46475465],
       [0.52733735, 0.32805285, 0.19577714, 0.63710811, 0.88395869],
       [0.52339265, 0.24096847, 0.64898614, 0.10972428, 0.84455517],
       [0.65376418, 0.89494027, 0.00635313, 0.00721045, 0.59824581]])