In [1]:
print("hello world")

hello world


In [2]:
print("this is jupyter notebook")

this is jupyter notebook


this is basic explaination

In [3]:
x=10
x

10

In [10]:
li1 = list(range(1,1001))

In [11]:
li2 = list(range(1,1001))

In [12]:
for i in range(1000):
    print(li1[i] + li2[i], end=' ')

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466 468 470 472 474 476 478 480 482 484 486 488 490 492 494 496 498 500 502 504 506 508 510 512 514 516 518 520 522 524 526 5

### Numpy
1. scrientific calculation library
2. huge data set of multidimensional array and matrix can be performed
3. liner algebra, random sampling, transformation
4. Python and C

In [13]:
import numpy as np

In [14]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

Homogenous

In [15]:
arr2 = np.array([1,2,3.14])
arr2

array([1.  , 2.  , 3.14])

In [16]:
arr3 = np.array([1,2,3.14,'a'])
arr3

array(['1', '2', '3.14', 'a'], dtype='<U32')

## Speed and operation

In [17]:
%%time
li1 = list(range(1,1000001))
li2 = list(range(1,1000001))
li3 = []
for i in range(1000000):
    li3.append(li1[i] + li2[i])

CPU times: total: 359 ms
Wall time: 365 ms


In [19]:
%%time
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)
arr1 + arr2

CPU times: total: 0 ns
Wall time: 13.2 ms


array([      2,       4,       6, ..., 1999996, 1999998, 2000000],
      shape=(1000000,))

### Size

In [21]:
import sys
sys.getsizeof(arr1)

8000112

In [22]:
li = []
sys.getsizeof(li)

56

In [23]:
arr = np.array([])
sys.getsizeof(arr)

112

In [24]:
li = [1,2,3,4]
sys.getsizeof(li)

88

In [25]:
arr = np.array([1,2,3,4])
sys.getsizeof(arr)

144

In [26]:
arr = np.array([])
sys.getsizeof(arr)

112

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.ndim

1

In [29]:
arr.dtype

dtype('float64')

In [30]:
arr

array([], dtype=float64)

In [31]:
arr = np.array([1,2,3,4])

In [32]:
arr.dtype

dtype('int64')

In [33]:
arr

array([1, 2, 3, 4])

In [34]:
arr.shape

(4,)

In [35]:
arr.size

4