## 1D

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30])

In [3]:
arr

array([10, 20, 30])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(3,)

In [10]:
arr = np.arange(1,5).reshape((4,))
arr

array([1, 2, 3, 4])

## 2D

In [6]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [7]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
arr1.ndim

2

In [9]:
arr1.shape

(3, 3)

In [11]:
arr2 = np.arange(1,10).reshape((3,3,))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3D

In [12]:
arr3 = np.arange(2,91,2).reshape((3,5,3))
arr3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24],
        [26, 28, 30]],

       [[32, 34, 36],
        [38, 40, 42],
        [44, 46, 48],
        [50, 52, 54],
        [56, 58, 60]],

       [[62, 64, 66],
        [68, 70, 72],
        [74, 76, 78],
        [80, 82, 84],
        [86, 88, 90]]])

In [13]:
arr3.ndim

3

In [14]:
arr3.shape

(3, 5, 3)

### linspace

In [15]:
lin = np.linspace(1,10,3)
lin

array([ 1. ,  5.5, 10. ])

### Ravel

In [17]:
arr3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24],
        [26, 28, 30]],

       [[32, 34, 36],
        [38, 40, 42],
        [44, 46, 48],
        [50, 52, 54],
        [56, 58, 60]],

       [[62, 64, 66],
        [68, 70, 72],
        [74, 76, 78],
        [80, 82, 84],
        [86, 88, 90]]])

In [18]:
arRavel = arr3.ravel()
arRavel

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

### Flatten

In [20]:
arr3.flatten("c")

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [21]:
arr3.flatten("F")

array([ 2, 32, 62,  8, 38, 68, 14, 44, 74, 20, 50, 80, 26, 56, 86,  4, 34,
       64, 10, 40, 70, 16, 46, 76, 22, 52, 82, 28, 58, 88,  6, 36, 66, 12,
       42, 72, 18, 48, 78, 24, 54, 84, 30, 60, 90])

### Transpose

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Metrics

## Ones

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Zeros

In [28]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Empty

In [29]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 6.23047842e-307],
       [2.22526399e-307, 2.05837348e-312]])

## Eye

In [31]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])