In [1]:
num = 5
fact = 1
while num > 0:
    fact = fact * num
    num -= 1
fact

120

In [2]:
num = int(input("enter the number"))

enter the number 12


In [3]:
num

12

In [6]:
a = -1
b = 1
n = int(input("enter the number:-"))
for i in range(n):
    c = a + b
    print(c, end=' ')
    a = b
    b = c
              

enter the number:- 12


0 1 1 2 3 5 8 13 21 34 55 89 

In [8]:
n = int(input("enter the number:-"))
first = 2
count = 0
while count < n:
    for i in range(2,first):
        if first % i == 0:
            first += 1
            break
    else:
        print(first, end=" ")
        first += 1
        count += 1

enter the number:- 10


2 3 5 7 11 13 17 19 23 29 

In [9]:
for i in range(1,5):
    for j in range(i):
        print("*", end=" ")
    print()

* 
* * 
* * * 
* * * * 


In [22]:
def fact(n):
    if n == 1:
        return 1
    else:
        return n + fact(n-1)

In [23]:
fact(5)

15

In [25]:
list1 = [10,22,38,40]
list2 = [5, 10,20,10]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
list3

[15, 32, 58, 50]

In [5]:
import numpy as np

# Addition

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr3 = arr1 + arr2
arr3


array([2, 4, 6, 8])

In [10]:
arr1 = np.array([2,'a','b','c'])
arr2 = np.array([4,'b','c','d'])
arr3 = arr1 + arr2
arr3

array(['24', 'ab', 'bc', 'cd'], dtype='<U42')

In [9]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr3 = arr1 // arr2
arr3

array([1, 1, 1, 1])

# Time Comparison

In [ ]:
%%time
li1 = [x for x in range(1,1001)]
li2 = [x for x in range(1001,2001)]
li3 = []
for i in range(len(li2)):
    li3.append(li1[i]+li2[i])
print(li3)

In [ ]:
%%time
arr1 = np.array(li1)
arr2 = np.array(li2)
arr3 = arr1 + arr2
print(arr3)

In [2]:
import numpy as np

# Memory Comparison

In [10]:
import sys

In [33]:
li = [1,2,3,4,5]
print(sys.getsizeof(li[0]*len(li)))

28


In [31]:
arr = np.array([1,2,3,4,5])
arr.itemsize*arr.size

40

## Functions

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,26)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [3]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
arr2 = np.random.rand(10)
arr2

array([0.67105763, 0.45681236, 0.95898879, 0.13026074, 0.16725861,
       0.43169463, 0.62232088, 0.39997686, 0.41293193, 0.03193525])

In [5]:
arr2 = np.random.rand(10).reshape(2,5)
arr2

array([[0.70398117, 0.18994157, 0.94270839, 0.09568499, 0.3480237 ],
       [0.81257339, 0.40759481, 0.92641581, 0.31855755, 0.52547218]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 5)

In [8]:
arr3 = np.random.randint(1,100,(3,5))
arr3

array([[51, 52, 99, 12, 61],
       [43, 57, 89, 51, 98],
       [57, 69, 64, 89, 89]], dtype=int32)

In [9]:
arr3 = np.random.randint(1,100,(5,2))
arr3

array([[94,  1],
       [88, 46],
       [69, 93],
       [57, 38],
       [28, 92]], dtype=int32)

In [10]:
arr4 = np.linspace(1,10)
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [11]:
arr4 = np.linspace(1,10,20)
arr4

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
arr5 = np.ones(5)
arr5

array([1., 1., 1., 1., 1.])

In [13]:
arr5 = np.ones(10).reshape(2,5)
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr6 = np.zeros(10,dtype=int).reshape(2,5)
arr6

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
arr7 = np.eye(4,dtype=str)
arr7

array([['1', '', '', ''],
       ['', '1', '', ''],
       ['', '', '1', ''],
       ['', '', '', '1']], dtype='<U1')

In [1]:
import numpy as np


In [2]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr[3:,2:]


array([[18, 19, 20],
       [23, 24, 25]])

In [11]:
li = [3,2,4,5,3,2]
li

[3, 2, 4, 5, 3, 2]

In [12]:
li[::-1]


[2, 3, 5, 4, 2, 3]

In [13]:
li = "diepsh"
li[::-1]


'hspeid'

In [14]:
li = [3,2,4,5,3,2]
new = []
for i in range(len(li)):
    if li[i] not in new:
        new.append(li[i])
new

[3, 2, 4, 5]

In [15]:
def sum(n):
    if n==1:
        return 1
    else:
        return n + sum(n-1) 

In [16]:
sum(5)

15

In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr.diagonal()

array([ 1,  7, 13, 19, 25])