In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape((3,3))
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2 = np.arange(2,11).reshape((3,3))
arr2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
np.add(arr1,arr2)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [5]:
arr1 + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [6]:
np.subtract(arr2,arr1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
arr2 - arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.multiply(arr1, arr2)

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [9]:
arr1 * arr2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [11]:
np.divide(arr2,arr1)

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [12]:
arr2 / arr1

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [13]:
np.dot(arr1,arr2)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [14]:
arr1 @ arr2

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [15]:
np.max(arr1)

np.int64(9)

In [16]:
np.max(arr1,axis=1)

array([3, 6, 9])

In [17]:
np.max(arr1,axis=0)

array([7, 8, 9])

In [18]:
arr1.max()

np.int64(9)